import React, { useState } from 'react'

interface GeneratedDua {
  title: string
  arabicText: string
  transliteration: string
  translation: string
  occasion: string
  benefits: string[]
  whenToRecite: string
  source: string
}

const DuaGenerator = () => {
  const [category, setCategory] = useState<'daily' | 'protection' | 'guidance' | 'health' | 'travel' | 'family'>('daily')
  const [situation, setSituation] = useState('')
  const [language, setLanguage] = useState('english')
  const [includePronunciation, setIncludePronunciation] = useState(true)
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedDua, setGeneratedDua] = useState<GeneratedDua | null>(null)

  const languages = [
    { code: 'english', name: 'English', flag: '🇺🇸' },
    { code: 'arabic', name: 'العربية', flag: '🇸🇦' },
    { code: 'turkish', name: 'Türkçe', flag: '🇹🇷' },
    { code: 'indonesian', name: 'Bahasa Indonesia', flag: '🇮🇩' },
    { code: 'urdu', name: 'اردو', flag: '🇵🇰' },
    { code: 'persian', name: 'فارسی', flag: '🇮🇷' },
    { code: 'bengali', name: 'বাংলা', flag: '🇧🇩' },
    { code: 'malay', name: 'Bahasa Melayu', flag: '🇲🇾' },
    { code: 'french', name: 'Français', flag: '🇫🇷' },
    { code: 'german', name: 'Deutsch', flag: '🇩🇪' }
  ]

  const categories = [
    { 
      id: 'daily', 
      icon: '🌅', 
      name: language === 'arabic' ? 'الأدعية اليومية' : 
            language === 'turkish' ? 'Günlük Dualar' : 
            language === 'indonesian' ? 'Doa Sehari-hari' : 
            'Daily Duas' 
    },
    { 
      id: 'protection', 
      icon: '🛡️', 
      name: language === 'arabic' ? 'أدعية الحماية' : 
            language === 'turkish' ? 'Koruma Duaları' : 
            language === 'indonesian' ? 'Doa Perlindungan' : 
            'Protection Duas' 
    },
    { 
      id: 'guidance', 
      icon: '🧭', 
      name: language === 'arabic' ? 'أدعية الهداية' : 
            language === 'turkish' ? 'Hidayet Duaları' : 
            language === 'indonesian' ? 'Doa Petunjuk' : 
            'Guidance Duas' 
    },
    { 
      id: 'health', 
      icon: '💚', 
      name: language === 'arabic' ? 'أدعية الصحة' : 
            language === 'turkish' ? 'Sağlık Duaları' : 
            language === 'indonesian' ? 'Doa Kesehatan' : 
            'Health Duas' 
    },
    { 
      id: 'travel', 
      icon: '✈️', 
      name: language === 'arabic' ? 'أدعية السفر' : 
            language === 'turkish' ? 'Seyahat Duaları' : 
            language === 'indonesian' ? 'Doa Perjalanan' : 
            'Travel Duas' 
    },
    { 
      id: 'family', 
      icon: '👨‍👩‍👧‍👦', 
      name: language === 'arabic' ? 'أدعية الأسرة' : 
            language === 'turkish' ? 'Aile Duaları' : 
            language === 'indonesian' ? 'Doa Keluarga' : 
            'Family Duas' 
    }
  ]

  const generateDua = async () => {
    setIsGenerating(true)
    
    // Simulate AI generation
    await new Promise(resolve => setTimeout(resolve, 2500))
    
    // Sample dua (would be generated by AI in real app)
    const dua: GeneratedDua = {
      title: language === 'arabic' ? 'دعاء الاستخارة' :
             language === 'turkish' ? 'İstihaре Duası' :
             language === 'indonesian' ? 'Doa Istikharah' :
             'Dua for Seeking Divine Guidance (Istikhara)',
      arabicText: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الْغُيُوبِ',
      transliteration: 'Allahumma innee astakheeruka bi-ilmika, wa astaqdiruka bi-qudratika, wa as\'aluka min fadlika al-adheem, fa-innaka taqdiru wa laa aqdir, wa ta\'lamu wa laa a\'lam, wa anta allaamul-ghuyoob',
      translation: language === 'arabic' ? 
        'اللهم إني أستخيرك بعلمك، وأستقدرك بقدرتك، وأسألك من فضلك العظيم، فإنك تقدر ولا أقدر، وتعلم ولا أعلم، وأنت علام الغيوب' :
        language === 'turkish' ?
        'Allah\'ım! İlminle senden hayırlı olanı istiyorum, kudretinle senden güç diliyorum, büyük fazlından istiyorum. Çünkü Sen güçlüsün, ben güçsüzüm; Sen bilirsin, ben bilmem; Sen gaybları bilensiz.' :
        language === 'indonesian' ?
        'Ya Allah, sesungguhnya aku meminta petunjuk kepada-Mu dengan ilmu-Mu, dan aku meminta kekuatan kepada-Mu dengan kekuatan-Mu, dan aku meminta kepada-Mu dari karunia-Mu yang agung. Sesungguhnya Engkau berkuasa dan aku tidak berkuasa, Engkau mengetahui dan aku tidak mengetahui, dan Engkau adalah Maha Mengetahui segala yang gaib.' :
        'O Allah, I seek Your guidance through Your knowledge, and I seek Your strength through Your power, and I ask of Your immense favor. For indeed You have power while I do not, You know while I do not, and You are the Knower of the unseen.',
      occasion: language === 'arabic' ? 'عند اتخاذ قرار مهم' :
               language === 'turkish' ? 'Önemli karar verirken' :
               language === 'indonesian' ? 'Ketika akan mengambil keputusan penting' :
               'When making important decisions',
      benefits: language === 'arabic' ? [
        'يساعد في اتخاذ القرارات الصحيحة',
        'يجلب السكينة والطمأنينة',
        'يقرب العبد من ربه',
        'يحمي من الندم على القرارات'
      ] : language === 'turkish' ? [
        'Doğru kararlar almaya yardım eder',
        'Huzur ve güven getirir',
        'Kulun Rabbine yaklaşmasını sağlar',
        'Kararlardan pişmanlık duyulmasını önler'
      ] : language === 'indonesian' ? [
        'Membantu mengambil keputusan yang tepat',
        'Mendatangkan ketenangan dan ketenteraman',
        'Mendekatkan hamba kepada Tuhannya',
        'Melindungi dari penyesalan atas keputusan'
      ] : [
        'Helps in making correct decisions',
        'Brings peace and tranquility',
        'Draws the servant closer to Allah',
        'Protects from regret over decisions'
      ],
      whenToRecite: language === 'arabic' ? 
        'يُقرأ بعد صلاة ركعتين نافلة، ويُفضل في الثلث الأخير من الليل. يمكن قراءته في أي وقت عند الحاجة لاتخاذ قرار مهم.' :
        language === 'turkish' ?
        'İki rekat nafile namazdan sonra okunur, gecenin son üçte birinde okunması tercih edilir. Önemli bir karar vermek gerektiğinde her zaman okunabilir.' :
        language === 'indonesian' ?
        'Dibaca setelah shalat sunnah dua rakaat, lebih baik di sepertiga malam terakhir. Dapat dibaca kapan saja ketika perlu mengambil keputusan penting.' :
        'Recited after performing two units of voluntary prayer, preferably in the last third of the night. Can be recited anytime when needing to make important decisions.',
      source: language === 'arabic' ? 'صحيح البخاري' :
              language === 'turkish' ? 'Sahih Buhari' :
              language === 'indonesian' ? 'Shahih Bukhari' :
              'Sahih al-Bukhari'
    }
    
    setGeneratedDua(dua)
    setIsGenerating(false)
  }

  const selectedLanguage = languages.find(l => l.code === language)

  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-green-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-amber-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button 
                onClick={() => window.history.back()}
                className="text-gray-600 hover:text-gray-900 transition-colors"
              >
                ← Back
              </button>
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 bg-gradient-to-r from-amber-500 to-amber-600 rounded-2xl flex items-center justify-center">
                  <span className="text-3xl">🤲</span>
                </div>
                <h1 className="text-2xl font-bold text-gray-900">AI Du'a Generator</h1>
              </div>
            </div>
            
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              className="bg-white border border-gray-300 rounded-lg px-4 py-2 font-medium focus:ring-2 focus:ring-amber-500"
            >
              {languages.map((lang) => (
                <option key={lang.code} value={lang.code}>
                  {lang.flag} {lang.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Description */}
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            {language === 'arabic' ? 'أدعية لكل حالة ومناسبة' :
             language === 'turkish' ? 'Her Durum ve Vesile için Dualar' :
             language === 'indonesian' ? 'Doa untuk Setiap Situasi dan Kesempatan' :
             'Duas for Every Situation and Occasion'}
          </h2>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            {language === 'arabic' ? 
              'اكتشف الأدعية المناسبة لحالتك مع النطق الصحيح والمعاني الشاملة والتوجيهات العملية.' :
             language === 'turkish' ?
              'Durumunuza uygun duaları doğru telaffuz, kapsamlı anlamlar ve pratik rehberlik ile keşfedin.' :
             language === 'indonesian' ?
              'Temukan doa yang sesuai dengan situasi Anda dengan pengucapan yang benar, makna yang komprehensif, dan panduan praktis.' :
              'Discover the perfect duas for your situation with correct pronunciation, comprehensive meanings, and practical guidance.'}
          </p>
          <div className="mt-4 inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full">
            <span className="mr-2">{selectedLanguage?.flag}</span>
            <span className="font-medium">{selectedLanguage?.name}</span>
          </div>
        </div>

        {/* Dua Generator Form */}
        <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100 mb-8">
          {/* Category Selection */}
          <div className="mb-8">
            <label className="block text-sm font-semibold text-gray-700 mb-4">
              {language === 'arabic' ? 'اختر فئة الدعاء' :
               language === 'turkish' ? 'Dua Kategorisi Seçin' :
               language === 'indonesian' ? 'Pilih Kategori Doa' :
               'Select Dua Category'}
            </label>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              {categories.map((cat) => (
                <button
                  key={cat.id}
                  onClick={() => setCategory(cat.id as any)}
                  className={`p-4 rounded-2xl font-medium transition-colors text-center ${
                    category === cat.id
                      ? 'bg-amber-600 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  <div className="text-3xl mb-2">{cat.icon}</div>
                  <div className="text-sm">{cat.name}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Specific Situation */}
          <div className="mb-8">
            <label className="block text-sm font-semibold text-gray-700 mb-3">
              {language === 'arabic' ? 'وصف الحالة (اختياري)' :
               language === 'turkish' ? 'Durum Açıklaması (Opsiyonel)' :
               language === 'indonesian' ? 'Deskripsi Situasi (Opsional)' :
               'Situation Description (Optional)'}
            </label>
            <textarea
              value={situation}
              onChange={(e) => setSituation(e.target.value)}
              placeholder={language === 'arabic' ? 'اكتب عن حالتك أو ما تحتاج إليه...' :
                         language === 'turkish' ? 'Durumunuzu veya neye ihtiyacınız olduğunu yazın...' :
                         language === 'indonesian' ? 'Tulis tentang situasi Anda atau apa yang Anda butuhkan...' :
                         'Describe your situation or what you need...'}
              className="w-full bg-white border border-gray-300 rounded-xl px-4 py-3 h-24 resize-none font-medium focus:ring-2 focus:ring-amber-500"
              dir={language === 'arabic' ? 'rtl' : 'ltr'}
            />
          </div>

          {/* Options */}
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-3">
                {language === 'arabic' ? 'خيارات إضافية' :
                 language === 'turkish' ? 'Ek Seçenekler' :
                 language === 'indonesian' ? 'Opsi Tambahan' :
                 'Additional Options'}
              </label>
              <div className="space-y-3">
                <label className="flex items-center">
                  <input 
                    type="checkbox" 
                    checked={includePronunciation}
                    onChange={(e) => setIncludePronunciation(e.target.checked)}
                    className="rounded text-amber-600 mr-3" 
                  />
                  <span className="text-sm text-gray-700">
                    {language === 'arabic' ? 'تضمين النطق باللاتينية' :
                     language === 'turkish' ? 'Latin harflerle telaffuz dahil et' :
                     language === 'indonesian' ? 'Sertakan pengucapan dengan huruf latin' :
                     'Include pronunciation guide'}
                  </span>
                </label>
                <label className="flex items-center">
                  <input type="checkbox" className="rounded text-amber-600 mr-3" defaultChecked />
                  <span className="text-sm text-gray-700">
                    {language === 'arabic' ? 'إظهار فوائد الدعاء' :
                     language === 'turkish' ? 'Duanın faydalarını göster' :
                     language === 'indonesian' ? 'Tampilkan manfaat doa' :
                     'Show benefits of the dua'}
                  </span>
                </label>
                <label className="flex items-center">
                  <input type="checkbox" className="rounded text-amber-600 mr-3" defaultChecked />
                  <span className="text-sm text-gray-700">
                    {language === 'arabic' ? 'تضمين الأوقات المستحبة' :
                     language === 'turkish' ? 'Önerilen zamanları dahil et' :
                     language === 'indonesian' ? 'Sertakan waktu yang dianjurkan' :
                     'Include recommended times'}
                  </span>
                </label>
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-3">
                {language === 'arabic' ? 'اختصارات سريعة' :
                 language === 'turkish' ? 'Hızlı Kısayollar' :
                 language === 'indonesian' ? 'Pintasan Cepat' :
                 'Quick Shortcuts'}
              </label>
              <div className="space-y-2">
                <button 
                  onClick={() => {setCategory('guidance'); setSituation('')}}
                  className="w-full text-left px-4 py-2 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                >
                  🧭 {language === 'arabic' ? 'دعاء الاستخارة' : 'Istikhara Dua'}
                </button>
                <button 
                  onClick={() => {setCategory('protection'); setSituation('')}}
                  className="w-full text-left px-4 py-2 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                >
                  🛡️ {language === 'arabic' ? 'أذكار الصباح والمساء' : 'Morning/Evening Adhkar'}
                </button>
                <button 
                  onClick={() => {setCategory('daily'); setSituation('')}}
                  className="w-full text-left px-4 py-2 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors text-sm"
                >
                  🍽️ {language === 'arabic' ? 'دعاء الطعام' : 'Mealtime Duas'}
                </button>
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <button
            onClick={generateDua}
            disabled={isGenerating}
            className="w-full bg-gradient-to-r from-amber-600 to-green-600 text-white py-4 px-8 rounded-2xl font-bold text-lg hover:from-amber-700 hover:to-green-700 transition-all duration-200 shadow-lg hover:shadow-xl disabled:opacity-50"
          >
            {isGenerating ? (
              <div className="flex items-center justify-center space-x-2">
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                <span>
                  {language === 'arabic' ? 'جاري البحث عن الدعاء...' :
                   language === 'turkish' ? 'Dua aranıyor...' :
                   language === 'indonesian' ? 'Mencari doa...' :
                   'Finding Perfect Dua...'}
                </span>
              </div>
            ) : (
              <>
                🤲 {language === 'arabic' ? 'إيجاد الدعاء المناسب' :
                     language === 'turkish' ? 'Uygun Duayı Bul' :
                     language === 'indonesian' ? 'Temukan Doa yang Tepat' :
                     'Find Perfect Dua'}
              </>
            )}
          </button>
        </div>

        {/* Generated Dua */}
        {generatedDua && (
          <div className="bg-white rounded-3xl p-8 shadow-xl border border-gray-100">
            {/* Dua Title */}
            <div className="text-center mb-8">
              <h3 className="text-3xl font-bold text-amber-600 mb-2">{generatedDua.title}</h3>
              <p className="text-lg text-gray-600">{generatedDua.occasion}</p>
              <div className="mt-2 inline-flex items-center px-3 py-1 bg-gray-100 text-gray-600 rounded-full text-sm">
                📖 {generatedDua.source}
              </div>
            </div>

            {/* Arabic Text */}
            <div className="bg-gradient-to-r from-amber-50 to-green-50 rounded-2xl p-8 mb-6">
              <h4 className="text-lg font-semibold text-gray-700 mb-4 text-center">
                {language === 'arabic' ? 'النص العربي' :
                 language === 'turkish' ? 'Arapça Metin' :
                 language === 'indonesian' ? 'Teks Arab' :
                 'Arabic Text'}
              </h4>
              <p className="text-2xl leading-relaxed text-center text-gray-900 mb-6" dir="rtl" style={{fontFamily: 'Amiri, serif'}}>
                {generatedDua.arabicText}
              </p>
              
              {/* Transliteration */}
              {includePronunciation && (
                <div className="border-t border-gray-200 pt-4">
                  <h5 className="text-sm font-semibold text-gray-600 mb-2">
                    {language === 'arabic' ? 'النطق' :
                     language === 'turkish' ? 'Telaffuz' :
                     language === 'indonesian' ? 'Pengucapan' :
                     'Pronunciation'}
                  </h5>
                  <p className="text-lg italic text-gray-700 leading-relaxed">
                    {generatedDua.transliteration}
                  </p>
                </div>
              )}
            </div>

            {/* Translation */}
            <div className="bg-blue-50 rounded-2xl p-6 mb-6">
              <h4 className="font-semibold text-blue-800 mb-3 flex items-center">
                <span className="mr-2">🌍</span>
                {language === 'arabic' ? 'الترجمة' :
                 language === 'turkish' ? 'Çeviri' :
                 language === 'indonesian' ? 'Terjemahan' :
                 'Translation'}
              </h4>
              <p className="text-blue-700 leading-relaxed text-lg" dir={language === 'arabic' ? 'rtl' : 'ltr'}>
                {generatedDua.translation}
              </p>
            </div>

            {/* Benefits and When to Recite */}
            <div className="grid md:grid-cols-2 gap-6 mb-6">
              {/* Benefits */}
              <div className="bg-green-50 rounded-2xl p-6">
                <h5 className="font-semibold text-green-800 mb-4 flex items-center">
                  <span className="mr-2">✨</span>
                  {language === 'arabic' ? 'فوائد هذا الدعاء' :
                   language === 'turkish' ? 'Bu Duanın Faydaları' :
                   language === 'indonesian' ? 'Manfaat Doa Ini' :
                   'Benefits of This Dua'}
                </h5>
                <ul className="space-y-2">
                  {generatedDua.benefits.map((benefit, index) => (
                    <li key={index} className="text-green-700 flex items-start" dir={language === 'arabic' ? 'rtl' : 'ltr'}>
                      <span className="mr-2 text-green-500">•</span>
                      {benefit}
                    </li>
                  ))}
                </ul>
              </div>

              {/* When to Recite */}
              <div className="bg-purple-50 rounded-2xl p-6">
                <h5 className="font-semibold text-purple-800 mb-4 flex items-center">
                  <span className="mr-2">⏰</span>
                  {language === 'arabic' ? 'متى يُقرأ' :
                   language === 'turkish' ? 'Ne Zaman Okunur' :
                   language === 'indonesian' ? 'Kapan Dibaca' :
                   'When to Recite'}
                </h5>
                <p className="text-purple-700 leading-relaxed" dir={language === 'arabic' ? 'rtl' : 'ltr'}>
                  {generatedDua.whenToRecite}
                </p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="text-center space-x-4">
              <button
                onClick={generateDua}
                className="bg-gradient-to-r from-amber-600 to-green-600 text-white py-3 px-6 rounded-2xl font-semibold hover:from-amber-700 hover:to-green-700 transition-all duration-200"
              >
                {language === 'arabic' ? 'دعاء آخر' :
                 language === 'turkish' ? 'Başka Dua' :
                 language === 'indonesian' ? 'Doa Lain' :
                 'Another Dua'}
              </button>
              <button className="bg-gray-100 text-gray-700 py-3 px-6 rounded-2xl font-semibold hover:bg-gray-200 transition-all duration-200">
                {language === 'arabic' ? 'حفظ الدعاء' :
                 language === 'turkish' ? 'Duayı Kaydet' :
                 language === 'indonesian' ? 'Simpan Doa' :
                 'Save Dua'}
              </button>
              <button className="bg-gray-100 text-gray-700 py-3 px-6 rounded-2xl font-semibold hover:bg-gray-200 transition-all duration-200">
                {language === 'arabic' ? 'مشاركة' :
                 language === 'turkish' ? 'Paylaş' :
                 language === 'indonesian' ? 'Bagikan' :
                 'Share'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default DuaGenerator